n_eval: 20
num_workers: 4
eval_type: "last" #"last"
save_summary: False
save_video: False

device: "cuda"
folder: "/home/weikang/LIBERO/libero/datasets"
bddl_folder: "libero/libero/bddl_files"
init_states_folder: "libero/libero/init_files"
experiment_dir: /home/weikang/workspace/robomimic_RW/experiments/RW1/SingleTask/BCTransformerPolicy_seed1904/run_001
#dataset_path: /home/weikang/LIBERO/libero/datasets/libero_spatial/pick_up_the_black_bowl_between_the_plate_and_the_ramekin_and_place_it_on_the_plate_demo.hdf5
dataset_path: /mnt/data0/rutavms/libero/rw_all/RW1_open_the_top_drawer_and_put_the_granola_bar_inside_it_demo.hdf5

interface_cfg: charmander.yml
folder_deoxys: "/tmp/deoxsys_demo_data"
controller_type: OSC_POSE
controller_cfg: osc-position-controller.yml