defaults:
  - _self_
  - repr: agentview_eye_in_hand_proprio_no_skip
  - agglomoration: defaults
  - skill_training: normal_subgoal
  - skill_subgoal_cfg: normal_subgoal
  - meta: normal_subgoal
  - meta_cvae_cfg: defaults
  - multitask: defaults
  - eval: defaults
  - video: defaults
exp_name: libero_object_goal
modality_str: dinov2_agentview_eye_in_hand
use_checkpoint: false
record_states: true
verbose: true
folder: ./
hydra:
    run:
        dir: .
 
